site_name: Proyecto FTTH - Kubernetes PoC
site_description: Documentación oficial de la Prueba de Concepto de FTTH en Kubernetes.
site_author: Sebastian Laborda

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - toc.integrate
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Cambiar a modo oscuro
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo claro

nav:
  - Inicio: index.md
  - Entorno Local: entorno.md
  - CI/CD (GitHub Actions): github-actions.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
