apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: redis-networkpolicy
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: ftth-redis
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ftth-backend
    ports:
    - protocol: TCP
      port: 6379
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
