apiVersion: v1
kind: Secret
metadata:
  name: ftth-registry-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  # Esto es un base64 dummy para {"auths":{"myprivateregistry.com":{"username":"dock_user","password":"dock_password","auth":"ZG9ja191c2VyOmRvY2tfcGFzc3dvcmQ="}}}
  .dockerconfigjson: eyJhdXRocyI6IHsibXlwcml2YXRlcmVnaXN0cnkuY29tIjogeyJ1c2VybmFtZSI6ICJkb2NrX3VzZXIiLCAicGFzc3dvcmQiOiAiZG9ja19wYXNzd29yZCIsICJhdXRoIjogIlpHOWphMTkxYzJWeU9tUnZZMnRmY0dGemMzZHZjbVE9In19fQ==
